//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace just_do_it_Web_API_Northwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spartan
    {
        public int SpartanID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UniversityAttended { get; set; }
        public string CourseTaken { get; set; }
        public Nullable<int> MarkAchieved { get; set; }
    }
}
